### ISSUE TITLE
TypeError: process.cwd is not a function

### ISSUE THREAD

**Issue by yoloz** [browserify/path-browserify#32]
vue3 + vite

```js
import { resolve } from 'path-browserify'
resolve(basePath, childpath)
```

```log
index.js:124  Uncaught (in promise) TypeError: process.cwd is not a function
    at resolve (index.js:124:25)
   ......
```

**Comment by yoloz** [comment]
issue #29 has solved, so close

**Comment by yoloz** [comment]
https://github.com/browserify/path-browserify/issues/29#issuecomment-1600002373 inject process, but browser err:
```log
Uncaught SyntaxError: The requested module '/@fs/xxx/node_modules/.pnpm/process@0.11.10/node_modules/process/browser.js?v=0ada4f31' does not provide an export named 'default'
```

**Comment by LuoRiWuSheng** [comment]
> vue3 + vite
> 
> ```js
> import { resolve } from 'path-browserify'
> resolve(basePath, childpath)
> ```
> 
> ```
> index.js:124  Uncaught (in promise) TypeError: process.cwd is not a function
>     at resolve (index.js:124:25)
>    ......
> ```

you can see  me  issue,  resolved

https://github.com/browserify/path-browserify/issues/34

**Comment by yoloz** [comment]
> > vue3 + vite
> > ```js
> > import { resolve } from 'path-browserify'
> > resolve(basePath, childpath)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > index.js:124  Uncaught (in promise) TypeError: process.cwd is not a function
> >     at resolve (index.js:124:25)
> >    ......
> > ```
> 
> you can see me issue, resolved
> 
> #34

yeah, i had  write a function too, this question want `path-browserify` support, thanks.
